[package]
org = "dasunorg"
name = "ai.aws.agentcore"
version = "0.1.0"
distribution = "2201.13.5"
authors = ["dasunorg"]
keywords = ["Type/Connector", "Vendor/Amazon", "Area/AI & Machine Learning", "Type/Long Term Memory Store", "Name/Amazon Bedrock AgentCore Memory"]
icon = "docs/icon.png"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true
